'use strict';
const fullName = 'Owen Adams';
const isCool = true;
const totalPets = 3;
console.log(`fullName: ${fullName}`);
console.log(`isCool: ${isCool}`);
console.log(`totalPets: ${totalPets}`);
console.log(`typeof fullName: ${typeof fullName}`);
console.log(`typeof isCool: ${typeof isCool}`);
console.log(`typeof totalPets: ${typeof totalPets}`);
const empty = null;
console.log(`empty: ${empty}`);
console.log(`typeof empty: ${typeof empty}`);
const nothing = undefined;
console.log(`nothing: ${nothing}`);
console.log(`typeof nothing: ${typeof nothing}`);
