'use strict';
const width = 5;
const height = 10;
const area = width * height;
console.log('value of area: ', area);
console.log('typeof area: ', typeof area);
const bill = 1999;
const payment = 2003;
const change = payment - bill;
console.log('value of change: ', change);
console.log('typeof change: ', typeof change);
const quizzes = 80;
const midterm = 95;
const final = 99;
const grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('typeof grade: ', typeof grade);
const firstName = 'Kenny';
const lastName = 'Powers';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName: ', fullName);
console.log('typeof fullName: ', typeof fullName);
const pH = 8;
const isAcidic = pH < 7;
console.log('value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof isAcidic);
const headCount = 1337;
const isSparta = headCount >= 300;
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
const motto = fullName + ' is the GOAT';
console.log('value of motto: ', motto);
console.log('typeof motto: ', typeof motto);
